Exécuter flutter build apk --release 

Exécution de la tâche Gradle 'assembleRelease'... 

ÉCHEC : La construction s’est terminée avec 2 échecs. 

1 : Échec de la tâche avec une exception. 
-----------
*Où: 
Fichier de compilation '/home/runner/work/gas_detector_app/gas_detector_app/android/app/build.gradle' ligne : 41 

* Ce qui n’a pas fonctionné : 
Un problème s’est produit lors de l’évaluation du projet ' :app'. 
> chemin d’accès ne doit pas être une chaîne nulle ou vide. path='null' 

*Essayer: 
> Exécutez avec l’option --stacktrace pour obtenir la trace de la pile. 
> Exécutez avec l’option --info ou --debug pour obtenir plus de sortie de journal. 
> Exécutez l’option --scan pour obtenir des informations complètes. 
> Obtenez plus d’aide sur https://help.gradle.org.
==============================================================================

2 : Échec de la tâche avec une exception. 
-----------
*Où: 
Fichier de compilation '/home/runner/work/gas_detector_app/gas_detector_app/android/app/build.gradle' ligne : 41 

* Ce qui n’a pas fonctionné : 
Un problème s’est produit lors de l’évaluation du projet ' :app'. 
> chemin d’accès ne doit pas être une chaîne nulle ou vide. path='null' 

*Essayer: 
> Exécutez avec l’option --stacktrace pour obtenir la trace de la pile. 
> Exécutez avec l’option --info ou --debug pour obtenir plus de sortie de journal. 
> Exécutez l’option --scan pour obtenir des informations complètes. 
> Obtenez plus d’aide sur https://help.gradle.org.
==============================================================================

ÉCHEC DE LA CONSTRUCTION en 1m 17s 
Exécution de la tâche Gradle 'assembleRelease'... 78,8 secondes 
Tâche Gradle assembleRelâcher avec le code de sortie 1 
Erreur: Processus terminé avec le code de sortie 1. 
