name: gas_detector_app
description: Application de détection de gaz avec base de données locale
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Stockage local
  shared_preferences: ^2.2.2

  # Icônes iOS
  cupertino_icons: ^1.0.2

  # Gestion d'état
  provider: ^6.0.5

  # Notifications locales (si tu les utilises toujours)
  flutter_local_notifications: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
