name: Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0' # ou ta version

      - name: Install dependencies
        run: flutter pub get

      # Crée key.properties à la racine du projet
    - name: Create key.properties file
    run: |
    echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > key.properties
    echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties
    echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
    echo "storeFile=android/app/upload-keystore.jks" >> key.properties

# Vérification (optionnel)
      - name: Check key.properties
        run: cat key.properties

      - name: Build APK release
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
